import { Poppins, Metrophobic } from "next/font/google";
import type { Metadata } from "next";
import { ThemeProvider } from "@/components/theme/theme-provider";
import { ThemeSwitcher } from "@/components/theme/theme-switcher";
import "./globals.css";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins",
});

const metrophobic = Metrophobic({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-metrophobic",
});

export const metadata: Metadata = {
  title: "Grapple BJJ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${poppins.variable} ${metrophobic.variable} font-sans`}>
        <ThemeProvider defaultTheme="system">
          <div className="min-h-screen">
            <header className="border-b">
              <div className="container flex items-center justify-between py-4">
                <h1 className="font-heading text-2xl font-bold">Grapple BJJ</h1>
                <ThemeSwitcher />
              </div>
            </header>
            <main className="container py-8">{children}</main>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
